server {
	#SSL/TLS Config
	listen 443 ssl;											# Depuis la version 1.12 de NGINX, il faut préciser ssl.
	ssl_protocols TLSv1.2 TLSv1.3;							# Gardons TLSv1.2 & TLSv1.3
	ssl_certificate /etc/nginx/ssl/inception.crt;			# Indiquons notre certificat
	ssl_certificate_key /etc/nginx/ssl/inception.key;		# et notre clef privée
	# root and index and server_name
	root /var/www/wordpress;										# Dossier racine de notre site
	server_name myevou.42.fr;									# Nom de notre serveur
	index index.php index.html index.htm;					# Index de notre site

	#location
	location / {
		try_files $uri $uri/ =404			;				# Essaye d'abord le fichier demandé, puis le dossier demandé, puis index.php
	}
	location ~ \,php$ {
		include snippets/fastcgi-php.conf;					# Inclut la configuration de PHP
		fastcgi_pass wordpress:9000;						# Envoie les requêtes PHP à notre container WordPress
	}
}


# server {
#     listen 443 ssl;
#     listen [::]:443 ssl;

#     server_name kdaumont.42.fr;

#     ssl_protocols TLSv1.3;
#     ssl_certificate /etc/nginx/ssl/inception.crt;
#     ssl_certificate_key /etc/nginx/ssl/inception.key;
    
#     add_header Strict-Transport-Security "max-age=0;";

#     index index.php;
#     root /var/www/html;

#     location / {
#         try_files $uri $uri/ /index.php$is_args$args;
#     }

#     location ~ \.php$ {
#         try_files $uri =404;
#         fastcgi_split_path_info ^(.+\.php)(/.+)$;
#         fastcgi_pass wordpress:9000;
#         fastcgi_index index.php;
#         include fastcgi_params;
#         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#         fastcgi_param PATH_INFO $fastcgi_path_info;
#     }
# }